spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1q2w3e4r
    url: jdbc:mysql://127.0.0.1:3306/funshop?characterEncoding=utf-8&useSSL=false
  jpa:
      open-in-view: true
      show-sql: true
banner:
  location: static/banner.txt
  charset: UTF-8