spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
      open-in-view: true
      show-sql: true
banner:
  location: static/banner.txt
  charset: UTF-8


---
spring:
  profiles: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 1q2w3e4r
      url: jdbc:mysql://127.0.0.1:3306/funshop?characterEncoding=utf-8&useSSL=false
server:
  port: 8089

---
spring:
  profiles: prod
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 1q2w3e4r
      url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
server:
  port: 8080
